>P1;tar
sequence:::::::::
SSFVPSQKTYPGNYGFRLGFLQSGTAKSVTCTYSPSLNKLFCQLAKTCPVQLWVDSPPP
PGTRVRAMAIYKKLEHMTEVVRRCPHHERSSDYSDGLAPPQHLIRVEGNLRAEYLDDRNT
FRHSVVVPYESPEIDSECTTIHYNFMCNSSCMGGMNRRPILTIITLEDSCGNLLGRNSFE
VRVCACPGRDRRTEEENLRKKGQSCPEPPPRSTKRALPTNTSSSPQPKKKPLDGEYFTLQ
IRGFKRYEMFRELNDALELKDALDG.
*

>P1;4mzr
structureX:4mzr:94:A:357:A::::
SSSVPSQKTYQGSYGFRLGFLHSGTAKFGTCTYSPALNKMFVQLAKTVPVQLYVDSTPP
PGTRVRAMAIYKQSQHMTEVVRRCPHHERSSD-SDGLAPPQHLIRVEGNLRAEYLDDPNT
FRHSVVVPYEPPEVGSDYTTIYFKFMCNSSCMGGMNRRPILVIITLEDSSGNLLGRDSFE
VRVCACPGRDRRTEEENLRKK-----------------------------TMDGEYFTLQ
IRGRERFEQFRERNEALELKDAQAT.
*
